### ISSUE TITLE
COCO embeddings

### ISSUE THREAD

**Issue by hanoonaR** [fcjian/PromptDet#2]
Hi,
Thank you for sharing your amazing work. 

Can you please share the embeddings used for COCO evaluation ? The LVIS-v1 has only 59 categories common with COCO. Otherwise could you share the learned 1 + 1 prompt vectors so it may be used in any dataset. 

Thank you.

**Comment by jianpursuit** [comment]
COCO category embeddings is shared in [here](https://github.com/fcjian/PromptDet/blob/master/embeddings/coco_category_embeddings.pt). 

The learned prompt and the code for prompt learning will be updated soon.

**Comment by fcjian** [comment]
COCO category embeddings are shared [here](https://github.com/fcjian/PromptDet/blob/master/embeddings/coco_category_embeddings.pt). 

The learned prompt and the code for prompt learning will be updated soon.

**Comment by hanoonaR** [comment]
Thank you for the quick response. 
@fcjian,  Could you please confirm if the shared COCO category embeddings are of the prompts with description concatenated with the learnable ones.

Thank you.

**Comment by fcjian** [comment]
Yes.
